eval:
  evolution_std: 0.001
  inherit_params: false
  max_steps: 10000
full_checkpoint_dir: /n/fs/vai-bwc-scr/saezdiez/other_files/class_stuff/COS435_final/PredPreyGrass/predpreygrass/rllib/nature/ckpt/174666872807888_3sp_w07
names:
  dir: ./ckpt
  project: pp
  raw_run_name: '{time}_{config_name}_w07'
plotting:
  html_dynamics: 10
run_name: 174666872807888_3sp_w07
ss:
  nr_cpus_for_main_process: 1
  nr_env_runners: 4
  nr_envs_per_env_runner: 1
  num_cpus_per_worker: 1
  num_gpus: 0
train:
  checkpoint_frequency: 20
  ckpt_to_keep: 1
  evolution_std: 0.001
  gamma: 0.99
  inherit_params: false
  lr: 0.0003
  max_steps: 1000
  num_sgd_iter: 1
  sgd_minibatch_size: 16
  train_batch_size: 128
  training_iterations: 2000
trophic_levels:
  baseline_energy_consumption: 0.025
  energy_cost_reproduction: 0.1
  energy_threshold_reproduction: 0.3
  frac_plants_to_animals: 1
  hunger_per_step: 0.005
  init_dist:
  - 0.85
  - 0.1
  - 0.05
  levels: 3
  levels_down_eat: 2
  low_energy_threshold: 0.15
  max_animals_per_species: 10000
  min_steps_between_reproduction: 5
  penalty_on_actions: 5
  reproduction_reward: 10
  reward_death: -200
  reward_eaten: 20
  sleep_cycles_range:
  - 1
  - 4
  species_per_level:
  - 1
  - 1
  - 1
  thirst_per_step: 0.005
world:
  grid_size: 20
  init_amount_animals: 0.3
  max_frac_covered_plants: 0.5
  max_obs: 21
  obs_channels: -1
  percentage_water: 8
  prob_plant_creates_plant: 0.01
  prob_random_plant_on_grid: 0.01
